//fetch data
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

//fetch data more
export const FETCH_DATA_MORE_SUCCESS = 'FETCH_DATA_MORE_SUCCESS';
export const FETCH_DATA_MORE_FAILURE = 'FETCH_DATA_MORE_FAILURE';

//filter data 
export const FILTER_SEARCH_DATA_SUCCESS = 'FILTER_SEARCH_DATA';
export const FILTER_SEARCH_DATA_FAILURE = 'FILTER_SEARCH_DATA';
